# Generated by Django 5.1.4 on 2024-12-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0003_alter_senha_fila'),
    ]

    operations = [
        migrations.AddField(
            model_name='senha',
            name='chamada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
